exp_arguments:
  # 类别数量
  n_classes: 2
  # 用于保存生成图像和资产的名称标签
  save_exp_code: HEATMAP_OUTPUT 
  # 保存原始资产文件的路径
  raw_save_dir: heatmaps/heatmap_raw_results
  # 保存最终热图的路径
  production_save_dir: heatmaps/heatmap_production_results
  # 批处理大小
  batch_size: 256

data_arguments: 
  # 数据存储位置；可以是一个字符串路径，也可以是键值对形式的字典映射
  data_dir: heatmaps/demo/slides/
  # data_dir 中键的列名称（如果使用字典映射）
  data_dir_key: source
  # 包含 slide_id 的 CSV 列表（可以额外包含分割/补丁参数、类别标签等）
  process_list: heatmap_demo_dataset.csv
  # 用于分割/补丁的预设文件
  preset: presets/bwh_biopsy.csv
  # 切片文件的扩展名
  slide_ext: .svs
  # 类别字典，用于字符串到整数的映射（可选）
  label_dict:
    LUAD: 0
    LSCC: 1                        

patching_arguments:
  # 补丁相关参数
  patch_size: 256  # 补丁大小
  overlap: 0.5     # 补丁之间的重叠比例
  patch_level: 0   # 分割时的金字塔层级
  custom_downsample: 1  # 自定义下采样比例

encoder_arguments:
  # 用于预训练编码器模型的参数
  model_name: resnet50_trunc # 当前支持：resnet50_trunc, uni_v1, conch_v1
  target_img_size: 224 # 在输入编码器之前，将图像调整为该大小

model_arguments: 
  # 从检查点初始化模型的参数
  ckpt_path: heatmaps/demo/ckpts/s_0_checkpoint.pt  # 检查点路径
  model_type: clam_sb # 见 utils/eval_utils/
  initiate_fn: initiate_model # 见 utils/eval_utils/
  model_size: small  # 模型大小
  drop_out: 0.  # dropout 比例
  embed_dim: 1024  # 嵌入维度

heatmap_arguments:
  # 可视化热图的下采样级别（-1 表示下采样到最接近 32 倍的下采样级别）
  vis_level: 1
  # 热图在背景上叠加的透明度（0：仅背景，1：仅前景）
  alpha: 0.4
  # 是否使用空白画布，而不是原始切片
  blank_canvas: false
  # 是否同时保存原始 H&E 图像
  save_orig: true
  # 热图/原始图像的保存文件扩展名
  save_ext: jpg
  # 是否计算相对于非重叠补丁集的百分位得分
  use_ref_scores: true
  # 是否使用高斯模糊进行进一步平滑
  blur: false
  # 是否移动默认的 4 个角点，用于检查补丁是否位于前景轮廓内
  use_center_shift: true
  # 是否仅计算指定 ROI（感兴趣区域）内的热图（x1, x2, y1, y2）
  use_roi: false 
  # 是否使用指定的重叠计算热图（默认情况下，始终计算没有重叠的粗热图）
  calc_heatmap: true
  # 是否对注意力分数进行二值化处理
  binarize: false
  # 二值化的阈值：(0, 1)
  binary_thresh: -1
  # 在最终显示前，热图的下采样因子
  custom_downsample: 1
  # 热图颜色映射
  cmap: jet

sample_arguments:
  samples:
    - name: "topk_high_attention"  # 采样名称
      sample: true  # 是否启用采样
      seed: 1  # 随机种子
      k: 15 # 保存前 k 个补丁
      mode: topk # 模式为 top-k
